### ISSUE TITLE
Possible to download from "My Files"?

### ISSUE THREAD

**Issue by Tscherno** [piejanssens/premiumizer#124]
I like to fully automate RSS downloading:
- RSS from RARBG => Torrent download to premiumize
- As soon as finished they go to my files (/Feed Downloads/feed name/torrent name/)
- Premiumizer should also download and delete them

Is there already an option to do so (which i didn't find...)? If not please add one, would be awesome!

**Comment by neox387** [comment]
#117

If u mean the RSS feature from premiumize.me instead of programs like sonarr/sickrage this also works yes. enable the option Download RSS feeds under Automatic Local Downloads.

> As soon as finished they go to my files (/Feed Downloads/feed name/torrent name/)

Feed name should be same as the category in premiumizer so /Feed Downloads/tv/torrent name for example then it will work.

**Comment by Tscherno** [comment]
How could i miss that...

Does it only work for new downloads or should it also grab the existing ones?

**Comment by neox387** [comment]
Should work for existing ones too I think, I'm not using it myself so not tested much ^^

You missed it because it's not in the readme yet, and we should have better documentation I guess :)
