### ISSUE TITLE
How to automatically set category?

### ISSUE THREAD

**Issue by gelsas** [piejanssens/premiumizer#159]
Hello,

I am using sonarr, what do I need to do to automatically send/set the category for premiumizer ?

**Comment by neox387** [comment]
Premiumizer settings:

Set your download location
By default category tv and movie exists
Enable Watchdir

For example
Download location: c:/download
Watchdir: c:/blackhole

You will have folder c:/blackhole/tv because the category exists and it creates the folder 


In sonarr:
Download client add torrent blackhole (enable save magnet option) and usenet blackhole will also work, put them in folder  c:/blackhole/tv

Do not use drone factory. 
Use nzbToMedia and set the path to nzbToMedia.py in premiumizer settings

Premiumizer will put the downloads in c:/download/tv in the above example

**Comment by gelsas** [comment]
I did that but when a download appeares in Premiumizer it shows that I need to select the category first (before that it doesn't continue)

**Comment by neox387** [comment]
If it's added outside premiumizer or trough the webinterface yes, if it's trough Watchdir in the appropiate folder (tv) it should set the category to tv by itself.
