### ISSUE TITLE
[Feature Request] add support for real-debrid too

### ISSUE THREAD

**Issue by GOvEy1nw** [piejanssens/premiumizer#261]
It'd be great if you could add support to RD, or make a seperate program for RD as I tend to use both Premiumize and RD alongside each other, as they often have different things cached, or if there's an issue with one, the other likely works etc. So it'd just expand the usability of this already fantastic program.

**Comment by sflix** [comment]
+1
I would love this too.

**Comment by tundrablasen** [comment]
Im getting this feature request back up.

Real-Debrid Support or a separate program would be great.
I think it should be possible since it has a good API documentation?
https://api.real-debrid.com/

Real Debrid has the advantages that it has unlimited downloads (Premiumize has 1tb per month)
Also it’s cheaper and more popular.

hope you would consider it
