### ISSUE TITLE
Not auto downloading on random files

### ISSUE THREAD

**Issue by 03184** [piejanssens/premiumizer#271]
Using current docker release, I am noticing that around 80-90% need me to manually click default button for file to download. I haven't had a chance to compare the files that do download automatically. Have included segment from debug log of a tv ep that failed. 
`today at 14:24  11-28 14:24:55: INFO : New watchdir file detected: /blackhole/Television.Episode.S01E02.(27.Nov.2020).720p.[subs].torrent
today at 14:24  11-28 14:24:55: INFO : Added: Television Episode S01E02 HDTV 720p x264-AAA.mkv -- Category:  -- Type: Torrent -- id: aaaaaaaaaa-aaaaaaaaaaa
today at 14:25  11-28 14:25:13: INFO : New watchdir file detected: /blackhole/Televison.Episode.S01E03.(27.Nov.2020).720p.[subs].torrent
today at 14:25  11-28 14:25:13: INFO : Added: Television Episode S61E197 HDTV 720p x264-AAA.mkv -- Category:  -- Type: Torrent -- id: aaaaaaaaaa-aaaaaaaaaaa
today at 14:28  Execution of job "update (trigger: interval[0:00:03], next run at: 2020-11-28 14:28:02 CET)" skipped: maximum number of running instances reached (1)
today at 14:38  11-28 14:38:05: WARNING : Download: Television Episode S61E197 HDTV 720p x264-AAA.mkv stuck restarting task
today at 14:38  Execution of job "update (trigger: interval[0:00:01], next run at: 2020-11-28 14:38:07 CET)" skipped: maximum number of running instances reached (1)`

**Comment by 03184** [comment]
Googling the error points to python apscheduler

**Comment by piejanssens** [comment]
Is this issue still occurring on the latest version/commit?

**Comment by neox387** [comment]
debug from first post the skipped: maximum number of running instances reached error can be ignored

it shows no category as the folder is /blackhole instead of something like /blackhole/tv/
so change the torrent folder in sonarr to  /blackhole/tv/ and see if you have a tv category in premiumizer.


this error seems to be an old pysmartdl version
> PySmartDL: WARNING : Server does not support HTTPRange. threads_count is set to 1

with latest version this is working:
01-09 18:36:24       root                                     : INFO     : Content-Length is 819448603 (781.5 MB).
01-09 18:36:24       root                                     : INFO     : Launching 10 threads (downloads 78.1 MB/thread).

so ye @03184 still have issues with latest build ?

**Comment by 03184** [comment]
tbh I gave up on premiumize, after their Black Friday sale they had all sorts of problems, the problem mentioned above ended up downloading 700+gb to their servers which maxed out my monthly limit after 1 day and they never responded to multiple Helpdesk questions. The category folder worked fine with ubuntu, there is definitely permission issues between windows/linux versions when it comes to sub directories, Windows version works as described, Linux version you can see on multiple threads here there are issues.

**Comment by neox387** [comment]
someone found and fixed a directory bug #275 so might be related

**Comment by neox387** [comment]
sorry this happened, normally the staff responds or they used to when I was asking api questions few years ago =D 
If you want to try again send me an email neox387@gmail.com :)
