### ISSUE TITLE
Windows cannot start service, and does not return an error.

### ISSUE THREAD

**Issue by attaboyBrad** [piejanssens/premiumizer#296]
Windows cannot start the Premiumizer service, and does not return an error. At least, that's what the error message says when I try to start the service manually.  The service Log On account is set to mine.

I can manually install Premiumizer just fine by following the instructions, but I've always had trouble with the Installer.

I've tried manually installing Git and Python to where the Installer wants them, because the Premiumizer installer often fails to install Git and Python properly, but that didn't help.  At one point after manually installing Python, python requested firewall access, which it hadn't done during my previous attempts where Python was supposed to be installed automatically as a dependency.  At long last this is what allowed me to at least get Premiumizer working by launching Premiumizer.py manually, but maybe other folks are having the same issue so I figured I'd post.

**Comment by neox387** [comment]
It is possible to get an error log for starting the service you need to enable it trough nssm that's in the installer directory:
Cmd
(location)/nssm edit Premiumizer
I/O and output it to a txt file some where to see what's going on

If you already had python or git installed before it's gonna fail, it's not isolated stand alone unfortunately.
I made it to hopefully help some people instead of a manual command line install or docker :)
