### ISSUE TITLE
naming issue

### ISSUE THREAD

**Issue by mohitjoshi155** [piejanssens/premiumizer#331]
my folders are getting named like name.torrent or name.nzb in downloads
anyway to disable folder getting extension names?

**Comment by neox387** [comment]
Is is not the same on premiimize.me website?

**Comment by leolobato** [comment]
I'm having the same issue but only on some torrents.

When it happens, the folder will be named `"this.is.the.filename.torrent"` (including the quotes) instead of the usual `this.is.the.filename` format, both on Premiumize and on Premiumizer.

Clicking on the dropbox that lets me choose the category on Premiumizer won't work for these items.

**Comment by neox387** [comment]
Looking at my downloads I noticed it too, however I have nzbtomedia picking up the files and sonarr moving them to correct folder. 

Been a while since I looked at the code but we use the file name premiuimze.me gives for the folder name, so either premiumize.me changed something or it's the tracker/indexer. 

It would be possible to implement to remove  .torrent/nzb from folder names before creating them in the code somewhere:) can check when I find some time

**Comment by leolobato** [comment]
OK, I just confirmed:

- On Premiumize *transfers*, the folder shows as `"this.is.the.filename.torrent"`
- On Premiumize *My Files*, the folder shows as `this.is.the.filename`
- On Premiumizer, the transfer shows as `"this.is.the.filename.torrent"`

**Comment by neox387** [comment]
> Clicking on the dropbox that lets me choose the category on Premiumizer won't work for these items. It will show the categories but nothing happens when I choose one.

Is weird tough, this should give something in the log or debug log maybe

**Comment by leolobato** [comment]
> Is weird tough, this should give something in the log or debug log maybe

Nothing shows up on the logs or debug logs. It's as if I didn't choose any category (and it still shows as the category was unselected).

**Comment by neox387** [comment]
Found the issue :)

**Comment by leolobato** [comment]
@neox387 Thanks for your fix, but the issue still happens for me even after updating. This only happens on some **magnet** links. To summarize:

- On Premiumize.me **Transfers**, the folder shows as `"this.is.the.filename.torrent"` (with quotes)
- On Premiumize.me **My Files**, the folder shows as `this.is.the.filename` (without quotes or the `.torrent` extension)
- On Premiumizer, the transfer shows as `"this.is.the.filename.torrent"`
- I can't pick a category to download it (nothing happens or shows on the logs)

**Comment by neox387** [comment]
Weird, so only on magnets links but not torrents? Would need to find one with .torrent on pm.me

**Comment by leolobato** [comment]
@neox387 just sent you an email with a magnet link where this happens 100% of the time.

**Comment by neox387** [comment]
I see this name has " so it ends on .torrent" instead of just .torrent

**Comment by leolobato** [comment]
It worked! Thanks, @neox387
