### ISSUE TITLE
jDownloader folder structure flattened

### ISSUE THREAD

**Issue by HammyHavoc** [piejanssens/premiumizer#332]
Hi,

According to https://board.jdownloader.org/showthread.php?p=489195, this seems to be possible to work around, although I've not managed it. The files still end up in the root folder, yet the sub-folders themselves are created, just have nothing in them.

**Comment by neox387** [comment]
Yea but that is something that uses the premiumize.me plugin in jDownloader to able to able to process a folder from premiumze.me

We give jDownloader the direct link for each file to download and this would already be a premium link.

However 2 things missing 1 is some extra code to check if this was a subfolder instead of 'path', easily implemented before:
download = {'path': os.path.join(path, clean_name(x['name'])), 'url': x['link']}

But the breaking one would be that you can not have files saving to different folders in the same container in jDownloader I think ? Having multiple packages for subfolder is going to break everything.

**Comment by ip-stivi** [comment]
Hi all, I am having this problem and so far haven't been able to figure out if the "problem" is coming from premiumizer or if it can be fixed with some settings from jdownloader. 
Basically, manually adding links to jdownloader from premiumize.me will preserve the folder structure but when adding the links through premiumizer it will flatten the structure and therefore creating problems with subtitle files (https://board.jdownloader.org/showthread.php?t=88180)

**Comment by neox387** [comment]
Try after PR
