### ISSUE TITLE
Create premiumizer.db file if not present

### ISSUE THREAD

**Issue by rb2k** [piejanssens/premiumizer#65]
I tested this on OSX according to the how-to:

```
12-18 16:23:11: ERROR : Uncaught exception
Traceback (most recent call last):
  File "./premiumizer.py", line 369, in <module>
    os.remove(os.path.join(runningdir, 'premiumizer.db'))
```

"touch premiumizer.db" fixed it

**Comment by neox387** [comment]
Did you cut last part of error? File doesn't exist or permission issue? 

1. If u stop premiumizer, delete the DB file and start again, you always get the same error? 

2. If nothing listed on home page aka nothing in the cloud and you restart not deleting the DB do you get the same error?

**Comment by neox387** [comment]
PR here, little optimization but wont fix your issue #66 

I don't have OS X to test, on windows deleting/opening database file works.
@piejanssens

**Comment by piejanssens** [comment]
@neox387 Why would this not fix his issue?

**Comment by neox387** [comment]
Before PR
1) db created
2) if db is empty: delete it & create it again (this is because I experienced some leftovers in the db after a while of usages although there where no db.keys.. 

After PR
1) if there is no db create it
2) else if there is a db file, open it check if it has no db.keys() if it doesn't, delete & recreate it.

but donno exactly what his error is, is there no db file & os.remove(os.path.join(runningdir, 'premiumizer.db')) tried to remove it ? if so os x did not make a db file with shelve.open(....) ? because he did touch premiumizer.db he made it himself ?

**Comment by piejanssens** [comment]
@rb2k Feel free to test after updating if it's solved for you and then please close this issue.

**Comment by rb2k** [comment]
This won't work, at least on OSX

```
>>> import shelve
>>> db = shelve.open('testing.db')
>>> db
{}
```

and

```
$ ls te*
testing.db.db
```


From the docs:

```
The filename specified is the base filename for the underlying database. As a side-effect, an extension may be added to the filename and more than one file may be created.
```

**Comment by neox387** [comment]
can u try 
````
import shelve
import anydbm
anydbm._defaultmod = __import__('dbhash')
db = shelve.open('testing.db')
````

& see if the filename is testing.db instead of testing.db.db like this ?

**Comment by neox387** [comment]
@rb2k Still have issues ? i'm guessing mac is still creating .db.db but premiumizer shouldn't be trying to delete '.db' file anymore if it doesn't exist :)
